# Generated by Django 5.0.1 on 2024-02-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ForeignKey(default=1, limit_choices_to={'id__lte': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='posts.postphotos'),
        ),
    ]
