# Generated by Django 5.0.1 on 2024-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_photos_post_photo_delete_postphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=10, unique=True)),
                ('post', models.ManyToManyField(to='posts.post')),
            ],
        ),
    ]
