# Generated by Django 5.0.1 on 2024-02-08 19:18

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_tag_post_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
